name: Bundle projext

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Upload source code artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: source
        path: .

    - name: Build
      run: |
        npm install -g pnpm
        pnpm install
        pnpm build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: bundle
        path: dist
